pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Maksimus1987/ML_OPs_HW_I'
            }
        }

        stage('Setup Environment') {
            steps {
                sh 'pip install -r lab_1/requirements.txt'
            }
        }

        stage('Data Creation') {
            steps {
                sh 'lab_1/data_creation.py'
            }
        }

        stage('Model Preparation') {
            steps {
                sh 'lab_1/model_preparation.py'
            }
        }

        stage('Model Preprocessing') {
            steps {
                sh 'lab_1/model_preprocessing.py'
            }
        }

        stage('Model Testing') {
            steps {
                sh 'lab_1/model_testing.py'
            }
        }
    }
}
      
